# This is a basic workflow to help you get started with Actions

name: getTaobaoInfo

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - master
  schedule: # 计划任务触发
    - cron: '* * * * *' 
    # cron表达式，时区是UTC时间，比我们早8小时，如上所表示的是每天0点0分（24点整）
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  getInfo:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: Production
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # 输出IP
      - name: IP
        run: sudo curl ifconfig.me
      - uses: actions/checkout@v2
      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: '^1.13.1'
      - run: go run main.go
